sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t indoorsy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true indoorsy/docker-react npm run test -- --coverage